# Assignment - 3_Q1

In [2]:
import pandas as pd
import numpy as np
from scipy import stats

In [3]:
cutlets = pd.read_csv ("C:/Users/BASHAR/OneDrive/Documents/Data Science/Assignment/Assignment - 3/Cutlets.csv")
cutlets

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [5]:
t_test = stats.ttest_rel(cutlets["Unit A"], cutlets["Unit B"])
t_test

Ttest_relResult(statistic=0.7536787225614314, pvalue=0.4562300768038412)

In [15]:
p_value = stats.ttest_ind(cutlets["Unit A"], cutlets["Unit B"])
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [17]:
p_value = p_value[1]
p_value

0.4722394724599501

In [18]:
if p_value <= 0.05:
    print("Reject H0, there is significant difference in the diameter of the cutlet between two units.")
else:
    print("Accept Ho, there is no significant difference in the diameter of the cutlet between two units.")

Accept Ho, there is no significant difference in the diameter of the cutlet between two units.


# Assignment - 3_Q2

In [20]:
labtat = pd.read_csv ("C:/Users/BASHAR/OneDrive/Documents/Data Science/Assignment/Assignment - 3/LabTAT.csv")
labtat

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [21]:
p_value = stats.f_oneway(labtat.iloc[:,0], labtat.iloc[:,1],labtat.iloc[:,2], labtat.iloc[:,3])
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [22]:
p_value = p_value[1]
p_value

2.1156708949992414e-57

In [23]:
if p_value <= 0.05:
    print("Reject H0, there is variance: Atleast one sample TAT population mean is different.")
else:
    print("Accept Ho, there is no variance: All samples TAT population means are same.")

Reject H0, there is variance: Atleast one sample TAT population mean is different.


# Assignment - 3_Q3

In [24]:
df = pd.read_csv ("C:/Users/BASHAR/OneDrive/Documents/Data Science/Assignment/Assignment - 3/BuyerRatio.csv")
df

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [25]:
df_table=df.iloc[:,1:5]
df_table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [26]:
df_table.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [27]:
val=stats.chi2_contingency(df_table)
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [28]:
Expected_value=val[3]
Expected_value

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [29]:
no_of_rows = len(df_table.iloc[0:2])
no_of_columns = len(df_table.iloc[0, 0:4])
DF = (no_of_rows-1)*(no_of_columns-1)
DF

3

In [30]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(df_table.values,Expected_value)])
chi_square

array([1.34226039e+00, 1.73035255e-01, 1.15612650e-04, 8.05342809e-02])

In [31]:
chi_square_statestic=chi_square[0]+chi_square[1]+chi_square[2]+chi_square[3]
chi_square_statestic

1.5959455386610577

In [32]:
critical_value=chi2.ppf(0.95,3)
critical_value

7.814727903251179

In [33]:
p_value=1-chi2.cdf(chi_square_statestic,3)
p_value

0.6603094907091882

In [34]:
if p_value <= 0.05:
    print("Reject H0, not all Proportions are equal.")
else:
    print("Accept Ho, all Proportions are equal.")

Accept Ho, all Proportions are equal.


# Assignment - 3_Q4

In [35]:
df = pd.read_csv("C:/Users/BASHAR/OneDrive/Documents/Data Science/Assignment/Assignment - 3/Costomer+OrderForm.csv")
df

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [36]:
df["Phillippines"].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [37]:
df["Indonesia"].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [38]:
df["Malta"].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [39]:
df["India"].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [40]:
obs=np.array([[271,267,269,280],[29,33,31,20]])
obs

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [41]:
from scipy.stats import chi2
val = stats.chi2_contingency(obs)
val

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [42]:
Expected_value = val[3]
Expected_value

array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]])

In [43]:
chi_square=sum([(o-e)**2/e for o,e in zip(obs,Expected_value)])
chi_square

array([0.02198142, 0.88169925, 0.295528  , 2.65975202])

In [44]:
chi_square_statestics = chi_square[0] + chi_square[1] + chi_square[2] + chi_square[3]
chi_square_statestics

3.8589606858203545

In [45]:
critical_value = stats.chi2.ppf(0.95,3)
critical_value

7.814727903251179

In [46]:
p_value = 1-stats.chi2.cdf(chi_square_statestics, 3)
p_value

0.2771020991233144

In [47]:
if p_value <= 0.05:
    print("Reject H0, customer order forms defective % varies by centre.")
else:
    print("Accept Ho, customer order forms defective % does not varies by centre")

Accept Ho, customer order forms defective % does not varies by centre
